// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdmn-CeGIjjODMH367TLOCohxV4z2LTe4',
    appId: '1:260654198138:web:70210dee1ee17f0f527ac3',
    messagingSenderId: '260654198138',
    projectId: 'pedro-f65a6',
    authDomain: 'pedro-f65a6.firebaseapp.com',
    storageBucket: 'pedro-f65a6.firebasestorage.app',
    measurementId: 'G-LQWPF54W2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBKOJLzRYpO1hJgCy8sSPdHNaIyeTRoCI',
    appId: '1:260654198138:android:bd1ed81efcde0ad2527ac3',
    messagingSenderId: '260654198138',
    projectId: 'pedro-f65a6',
    storageBucket: 'pedro-f65a6.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp6mhShMWc-lvwa-sw4Y_VBlitP18kvAo',
    appId: '1:260654198138:ios:605e1e7955b0fb52527ac3',
    messagingSenderId: '260654198138',
    projectId: 'pedro-f65a6',
    storageBucket: 'pedro-f65a6.firebasestorage.app',
    androidClientId: '260654198138-tcjr0mhikksjd517apgpsljdk8s87j94.apps.googleusercontent.com',
    iosClientId: '260654198138-tr8fhmvb09r33tef7278c3l3il9aa615.apps.googleusercontent.com',
    iosBundleId: 'com.ool.pedro',
  );
}
